webcommand:
    resource: "@WebcommandBundle/Controller/"
    type:     annotation
    prefix:   /

banckend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

#fos user bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /administration/dashboard/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /administration/dashboard/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#url base para adminsitracao
fos_user_security_login:
    path:      /
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }
