# jms_security_extra:
#     secure_all_services: false
#     expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_MANAGER: ROLE_ADMIN
        ROLE_SIMPLE: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        nc:
            pattern: /nc(.*)
            form_login:
                login_path: /nc/login
                check_path: /nc/login_check
                default_target_path: "/administration/dashboard"
                failure_path: /nc/login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                target: /
            anonymous: true
        main:
            pattern: ^/
            form_login:
                default_target_path: "/administration/dashboard"
                failure_path: /
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                target: /
            anonymous: true

    access_control:
        # so usuario nao autenticado pode fazer login
        # - { path: ^/login$, roles: IS_AUTHENTIFICATED_ANONYMOUSLY }
        - { path: ^/administration, roles: ROLE_USER }
        - { path: ^/administration/dashboard, roles: ROLE_USER }
        # - { path: ^/administration/admin, roles: ROLE_ADMIN }

# access_control:
#     - { path: ^/login, roles: IS_AUTHENTIFICATED_ANONYMOUSLY }
#     - { path: ^/*, roles: ROLE_ADMIN }
