# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  sga.admin.table.pagination:
      class: Admin\Backend\Model\Pagination
      arguments: [@service_container]

  sga.admin.filter:
      class: Admin\Backend\Model\Filter
      arguments: [@service_container]
