backend_administration_user:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix:   /administration/user

backend_administration_category:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix:   /administration/category

sga_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Security:login }

sga_dashboard:
    path:     /administration/dashboard
    defaults: { _controller: BackendBundle:Default:index }
