backend_administration_discipline:
    resource: "@BackendBundle/Resources/config/routing/discipline.yml"
    prefix:   /administration/discipline

backend_administration_category:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix:   /administration/category

backend_course:
    resource: "@BackendBundle/Resources/config/routing/course.yml"
    prefix:   /administration/course

sga_homepage:
    path:     /
    # XXX: create a Homepage
    defaults: { _controller: BackendBundle:Security:login }

sga_dashboard:
    path:     /administration/dashboard
    defaults: { _controller: BackendBundle:Default:index }

sga_login:
    path:     /security/login
    defaults: { _controller: BackendBundle:Security:login }
