backend_administration_userHasRole:
    resource: "@BackendBundle/Resources/config/routing/userhasrole.yml"
    prefix:   /administration/userHasRole

backend_administration_role:
    resource: "@BackendBundle/Resources/config/routing/role.yml"
    prefix:   /administration/role

backend_administration_user:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix:   /administration/user

backend_administration_course:
    resource: "@BackendBundle/Resources/config/routing/course.yml"
    prefix:   /administration/course

backend_administration_klass:
    resource: "@BackendBundle/Resources/config/routing/klass.yml"
    prefix:   /administration/klass

backend_administration_classroom:
    resource: "@BackendBundle/Resources/config/routing/classroom.yml"
    prefix:   /administration/classroom

backend_administration_discipline:
    resource: "@BackendBundle/Resources/config/routing/discipline.yml"
    prefix:   /administration/discipline

backend_administration_category:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix:   /administration/category

sga_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Security:login }

sga_dashboard:
    path:     /administration/dashboard
    defaults: { _controller: BackendBundle:Default:index }
