backend_administration_UserProfile:
    resource: "@BackendBundle/Resources/config/routing/userprofile.yml"
    prefix:   /administration/UserProfile

backend_administration_Document:
    resource: "@BackendBundle/Resources/config/routing/document.yml"
    prefix:   /administration/Document

backend_administration_Complaint:
    resource: "@BackendBundle/Resources/config/routing/complaint.yml"
    prefix:   /administration/Complaint

backend_administration_Sugestion:
    resource: "@BackendBundle/Resources/config/routing/sugestion.yml"
    prefix:   /administration/Sugestion

backend_administration_StageProfile:
    resource: "@BackendBundle/Resources/config/routing/stageprofile.yml"
    prefix:   /administration/StageProfile

backend_administration_ModuleStage:
    resource: "@BackendBundle/Resources/config/routing/modulestage.yml"
    prefix:   /administration/ModuleStage

backend_administration_Stage:
    resource: "@BackendBundle/Resources/config/routing/stage.yml"
    prefix:   /administration/Stage

backend_administration_Profile:
    resource: "@BackendBundle/Resources/config/routing/profile.yml"
    prefix:   /administration/Profile

backend_administration_Module:
    resource: "@BackendBundle/Resources/config/routing/module.yml"
    prefix:   /administration/Module

backend_administration_entities:
    resource: "@BackendBundle/Resources/config/routing/appentity.yml"
    prefix:   /administration/entities

backend_administration_category:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix:   /administration/category

backend_administration_sugestao:
    resource: "@BackendBundle/Resources/config/routing/sugestao.yml"
    prefix:   /administration/sugestao

backend_administration_user:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix:   /administration/user

backend_administration_main:    
    path:  /administration/main
    defaults:  { _controller: BackendBundle:Admin:index }

backend_administration_main_profiles:    
    path:  /administration/profiles_of/{id}
    defaults:  { _controller: BackendBundle:Admin:profiles }

backend_administration_main_profiles_remove:    
    path:  /administration/remove_userp/{id}
    defaults:  { _controller: BackendBundle:Admin:removeUserProfile }

dashboard_stats:
    path:     /dashboard/stats/{type}
    defaults: { _controller: BackendBundle:Default:stats }

sga_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Security:login }

sga_dashboard:
    path:     /administration/dashboard
    defaults: { _controller: BackendBundle:Default:index }
