administrator_category:
    path:     /
    defaults: { _controller: "BackendBundle:Category:index" }

administrator_category_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Category:show" }

administrator_category_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Category:new" }

administrator_category_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Category:create" }
    methods:  POST

administrator_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Category:edit" }

administrator_category_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Category:update" }
    methods:  [POST, PUT]

administrator_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Category:delete" }
    methods:  [POST, DELETE]
