course:
    path:     /
    defaults: { _controller: "BackendBundle:Course:index" }

course_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Course:show" }

course_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Course:new" }

course_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Course:create" }
    methods:  POST

course_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Course:edit" }

course_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Course:update" }
    methods:  [POST, PUT]

course_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Course:delete" }
    methods:  [POST, DELETE]
