administration_discipline:
    path:     /
    defaults: { _controller: "BackendBundle:Discipline:index" }

administration_discipline_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Discipline:show" }

administration_discipline_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Discipline:new" }

administration_discipline_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Discipline:create" }
    methods:  POST

administration_discipline_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Discipline:edit" }

administration_discipline_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Discipline:update" }
    methods:  [POST, PUT]

administration_discipline_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Discipline:delete" }
    methods:  [POST, DELETE]
