administration_IReclamation:
    path:     /
    defaults: { _controller: "BackendBundle:IReclamation:index" }

administration_IReclamation_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:IReclamation:show" }

administration_IReclamation_new:
    path:     /new
    defaults: { _controller: "BackendBundle:IReclamation:new" }

administration_IReclamation_create:
    path:     /create
    defaults: { _controller: "BackendBundle:IReclamation:create" }
    methods:  POST

administration_IReclamation_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:IReclamation:edit" }

administration_IReclamation_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:IReclamation:update" }
    methods:  [POST, PUT]

administration_IReclamation_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:IReclamation:delete" }
    methods:  [POST, DELETE]
