administration_role:
    path:     /
    defaults: { _controller: "BackendBundle:Role:index" }

administration_role_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Role:show" }

administration_role_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Role:new" }

administration_role_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Role:create" }
    methods:  POST

administration_role_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Role:edit" }

administration_role_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Role:update" }
    methods:  [POST, PUT]

administration_role_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Role:delete" }
    methods:  [POST, DELETE]
