administration_Sugestion:
    path:     /
    defaults: { _controller: "BackendBundle:Sugestion:index" }

administration_Sugestion_byState:
    path:     /{state}
    defaults: { _controller: "BackendBundle:Sugestion:byState" }

administration_Sugestion_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Sugestion:show" }

administration_Sugestion_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Sugestion:new" }

administration_Sugestion_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Sugestion:create" }
    methods:  POST

administration_Sugestion_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Sugestion:edit" }

administration_Sugestion_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Sugestion:update" }
    methods:  [POST, PUT]

administration_Sugestion_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Sugestion:delete" }
    methods:  [POST, DELETE]
