administration_TeacherDiscipline:
    path:     /
    defaults: { _controller: "BackendBundle:TeacherDiscipline:index" }

administration_TeacherDiscipline_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:TeacherDiscipline:show" }

administration_TeacherDiscipline_new:
    path:     /new
    defaults: { _controller: "BackendBundle:TeacherDiscipline:new" }

administration_TeacherDiscipline_create:
    path:     /create
    defaults: { _controller: "BackendBundle:TeacherDiscipline:create" }
    methods:  POST

administration_TeacherDiscipline_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:TeacherDiscipline:edit" }

administration_TeacherDiscipline_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:TeacherDiscipline:update" }
    methods:  [POST, PUT]

administration_TeacherDiscipline_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:TeacherDiscipline:delete" }
    methods:  [POST, DELETE]
