administration_userHasRole:
    path:     /
    defaults: { _controller: "BackendBundle:UserHasRole:index" }

administration_userHasRole_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:UserHasRole:show" }

administration_userHasRole_new:
    path:     /new
    defaults: { _controller: "BackendBundle:UserHasRole:new" }

administration_userHasRole_create:
    path:     /create
    defaults: { _controller: "BackendBundle:UserHasRole:create" }
    methods:  POST

administration_userHasRole_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:UserHasRole:edit" }

administration_userHasRole_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:UserHasRole:update" }
    methods:  [POST, PUT]

administration_userHasRole_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:UserHasRole:delete" }
    methods:  [POST, DELETE]
