administration_UserHasKlass:
    path:     /
    defaults: { _controller: "BackendBundle:UserHasKlass:index" }

administration_UserHasKlass_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:UserHasKlass:show" }

administration_UserHasKlass_new:
    path:     /new
    defaults: { _controller: "BackendBundle:UserHasKlass:new" }

administration_UserHasKlass_create:
    path:     /create
    defaults: { _controller: "BackendBundle:UserHasKlass:create" }
    methods:  POST

administration_UserHasKlass_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:UserHasKlass:edit" }

administration_UserHasKlass_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:UserHasKlass:update" }
    methods:  [POST, PUT]

administration_UserHasKlass_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:UserHasKlass:delete" }
    methods:  [POST, DELETE]
