TblAluno:
    type: entity
    table: tbl_aluno
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Nome
        habalitacaoLiteraria:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Habalitacao_literaria
        cargo:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Cargo
        nif:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Nif
        sexo:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Sexo
        email:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Email
        telemovel:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Telemovel
        telefone:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Telefone
        moradaAtual:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: 'Morada Atual'
        dataNascimento:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Data_Nascimento
        nomePai:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Nome_Pai
        nomeMai:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Nome_Mai
        telefonePai:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Telefone_pai
        telemovelMai:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Telemovel_Mai
        moradaPai:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Morada_pai
        moradaMai:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Morada_Mai
        emailMae:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: 'Email Mae'
        emailPai:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: 'Email Pai'
    lifecycleCallbacks: {  }
