TblDesciplinaCurso:
    type: entity
    table: tbl_desciplina_curso
    indexes:
        fk_tbl_desciplina_has_tbl_curso_tbl_curso1_idx:
            columns:
                - tbl_curso_id
        fk_tbl_desciplina_has_tbl_curso_tbl_desciplina1_idx:
            columns:
                - tbl_desciplina_id
    id:
        id:
            type: string
            nullable: false
            length: 45
            fixed: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        tblCurso:
            targetEntity: TblCurso
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbl_curso_id:
                    referencedColumnName: id
            orphanRemoval: false
        tblDesciplina:
            targetEntity: TblDesciplina
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbl_desciplina_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
