TblDomain:
    type: entity
    table: tbl_domain
    id:
        idDomain:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_domain
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Descricao
        valor:
            type: string
            nullable: true
            length: 45
            fixed: false
        tipo:
            type: string
            nullable: true
            length: 45
            fixed: false
    lifecycleCallbacks: {  }
