TblFuncao:
    type: entity
    table: tbl_funcao
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Descricao
    lifecycleCallbacks: {  }
