TblInstrutor:
    type: entity
    table: tbl_instrutor
    indexes:
        fk_tbl_instrutor_tbl_area1_idx:
            columns:
                - tbl_area_id
        fk_tbl_instrutor_tbl_funcionario1_idx:
            columns:
                - tbl_funcionario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Nome
        idade:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Idade
        telefone:
            type: string
            nullable: true
            length: 45
            fixed: false
        email:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Email
        morada:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: Morada
    manyToOne:
        tblArea:
            targetEntity: TblArea
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbl_area_id:
                    referencedColumnName: id
            orphanRemoval: false
        tblFuncionario:
            targetEntity: TblFuncionario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbl_funcionario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
