TblPerfil:
    type: entity
    table: tbl_perfil
    id:
        idPerfil:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_perfil
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 50
            fixed: false
        descricao:
            type: string
            nullable: true
            length: 50
            fixed: false
        estado:
            type: string
            nullable: true
            length: 1
            fixed: false
        codigo:
            type: string
            nullable: true
            length: 20
            fixed: false
    lifecycleCallbacks: {  }
