TblUsers:
    type: entity
    table: tbl_users
    indexes:
        fk_tbl_users_tbl_perfil1:
            columns:
                - tbl_perfil_id_perfil
    id:
        idUser:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_user
            generator:
                strategy: IDENTITY
    fields:
        utilizador:
            type: string
            nullable: true
            length: 50
            fixed: false
        palavraPasse:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: palavra_passe
        email:
            type: string
            nullable: true
            length: 30
            fixed: false
        estado:
            type: string
            nullable: true
            length: 1
            fixed: false
        contacto:
            type: string
            nullable: true
            length: 20
            fixed: false
        horaUltimoLogin:
            type: integer
            nullable: true
            unsigned: false
            column: hora_ultimo_login
        data:
            type: date
            nullable: true
        nomeCompleto:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: nome_completo
        morada:
            type: string
            nullable: true
            length: 25
            fixed: false
    manyToOne:
        tblPerfilPerfil:
            targetEntity: TblPerfil
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tbl_perfil_id_perfil:
                    referencedColumnName: id_perfil
            orphanRemoval: false
    lifecycleCallbacks: {  }
