User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        utilizador:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 1050
            fixed: false
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        estado:
            type: boolean
            nullable: false
        ultimoLogin:
            type: datetime
            nullable: true
            column: ultimo_login
    lifecycleCallbacks: {  }
